#!/usr/bin/env  bash
#ananananananana
#Bash script that transfers a file from our client to a server.

if [ $# -lt 4 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # scp -o $HOST_KEY -i "$PATH_TO_SSH_KEY"  $PATH_TO_FILE $USERNAME@$IP:~/
    scp -o StrictHostKeyChecking=no -i "$4"  "$1" "$3"@"$2":~/

fi
