#!/usr/bin/env  bash
#Bash script that transfers a file from our client to a server.

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4
HOST_KEY=StrictHostKeyChecking=no


if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # scp -o $HOST_KEY -i "$PATH_TO_SSH_KEY"  $PATH_TO_FILE $USERNAME@$IP:~/
    scp -o $HOST_KEY -i "$PATH_TO_SSH_KEY"  "$PATH_TO_FILE" "$USERNAME"@"$IP":~

fi
